Fix MudPopover countProviders
Whenever the `mainContainerClass` is null because the `initialize` method was not yet called, the countProviders should return 0.

If any element on the page has a class named `null` then the count will be greater than 0. When the popover provider is not initialized, the `countProviders` method evaluates to `document.querySelectorAll(".null")`. This will return the count of elements having a class named `null`.

This can easily happen when using the the [CodeBeam.MudBlazor.Extensions.Code](https://www.nuget.org/packages/CodeBeam.MudBlazor.Extensions.Code) package and formatting JSON which contains `null` tokens. Here's how `null` tokens are rendered:

```html
<span class="token null keyword">null</span>
```

And we end up with this (false positive) exception:

> InvalidOperationException: Duplicate MudPopoverProvider detected. Please ensure there is only one provider, or disable this warning with PopoverOptions.ThrowOnDuplicateProvider.